name: evcoownership
publish_to: 'none'
description: EV Co-ownership & Cost-sharing – Flutter UI skeleton
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.4.0
  get_it: ^7.6.7
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  go_router: ^14.2.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
